###################### Filebeat Configuration (Nginx + Postgres) #########################

# ============================== Filebeat inputs ===============================

filebeat.inputs:

# 1. Логи Nginx (Добавлено нами)
- type: log
  enabled: true
  paths:
    - /var/log/nginx/access.log
    - /var/log/nginx/error.log
  fields:
    type: nginx_access

# 2. Стандартный инпут (был у тебя, оставим выключенным, как было)
- type: filestream
  id: my-filestream-id
  enabled: false
  paths:
    - /var/log/*.log

# ============================== Filebeat modules ==============================

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

# ======================= Elasticsearch template setting =======================

setup.template.settings:
  index.number_of_shards: 1

# =================================== Kibana ===================================

setup.kibana:
  host: "http://localhost:5601"

# ================================== Outputs ===================================

# ---------------------------- Elasticsearch Output ----------------------------
output.elasticsearch:
  hosts: ["https://localhost:9200"]
  preset: balanced
  protocol: "https"
  username: "elastic"
  # Твой пароль (в реальном продакшене лучше использовать Ansible Vault, но для демо ок)
  password: "ULWsoqLir92SHxMj8X+4"
  ssl.verification_mode: none

# ================================= Processors =================================
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~

# ================================= Migration ==================================

migration.6_to_7.enabled: true

# ========================== PostgreSQL Module (Твой) ==========================
# Оставляем этот блок, чтобы логи базы данных продолжали идти
filebeat.modules:
- module: postgresql
  log:
    enabled: true
    var.paths: ["/var/lib/postgresql/18/main/log/*.log"]
