---
- name: Configure Nginx and Filebeat
  hosts: db_servers
  become: yes
  
  tasks:
    # --- Настройка времени (Добавляем это) ---
    - name: Set timezone to Europe/Warsaw
      timezone:
        name: Europe/Warsaw  # <-- Замени на свой город (Europe/Minsk, Europe/Moscow и т.д.)
    # 1. Установка Nginx (если вдруг нет)
    - name: Ensure Nginx is installed
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Ensure Nginx is running
      service:
        name: nginx
        state: started
        enabled: yes

    # 2. Обновление конфига Filebeat
    # Мы копируем наш объединенный файл поверх старого
    - name: Upload merged Filebeat configuration
      copy:
        src: filebeat.yml
        dest: /etc/filebeat/filebeat.yml
        owner: root
        group: root
        mode: '0644'
      notify: Restart Filebeat

  # Перезапуск произойдет только если файл изменился
  handlers:
    - name: Restart Filebeat
      service:
        name: filebeat
        state: restarted
